# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # good practices
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true

    #clean code
    unnecessary_null_checks: true
    prefer_single_quotes: true
    sort_child_properties_last: true

    always_declare_return_types: true      # all methods must have explicit return type
    annotate_overrides: true               # @override must always be present
    avoid_empty_else: true                 # no empty else blocks
    avoid_redundant_argument_values: true  # don't pass unnecessary default values
    camel_case_types: true                 # classes in CamelCase
    file_names: true                       # files in snake_case
    prefer_is_empty: true                  # use list.isEmpty instead of list.length == 0
    

